# Generated by Django 3.0.4 on 2020-04-07 08:09

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SmulWebPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_url', models.CharField(max_length=50)),
                ('page_nr', models.IntegerField(default='0')),
            ],
        ),
        migrations.CreateModel(
            name='SmulWebRecipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_url', models.CharField(max_length=2000)),
                ('recipe_JSON', django.contrib.postgres.fields.jsonb.JSONField()),
                ('page_url', models.ForeignKey(db_column='page_url', on_delete=django.db.models.deletion.CASCADE, to='collector.SmulWebPage')),
            ],
        ),
    ]
