# Generated by Django 3.0.4 on 2020-03-26 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='smulwebpage',
            name='page_nr',
            field=models.IntegerField(default='0'),
        ),
    ]
