# Generated by Django 3.0.4 on 2020-03-26 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0002_smulwebpage_page_nr'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmulWebRecipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_text', models.CharField(max_length=2000)),
                ('titel_gerecht', models.CharField(max_length=2000)),
                ('url', models.CharField(max_length=2000)),
                ('keuken', models.CharField(max_length=2000)),
                ('gang', models.CharField(max_length=2000)),
                ('tijdsduur', models.CharField(max_length=2000)),
                ('datum', models.CharField(max_length=2000)),
                ('intro', models.CharField(max_length=2000)),
                ('recepttekst', models.CharField(max_length=2000)),
                ('plaatser_naam', models.CharField(max_length=2000)),
                ('plaatser_url', models.CharField(max_length=2000)),
                ('plaatser_volgers', models.IntegerField(blank=True, null=True)),
                ('plaatser_recepten', models.IntegerField(blank=True, null=True)),
                ('plaatser_kookboeken', models.IntegerField(blank=True, null=True)),
                ('ingredienten', models.CharField(max_length=2000)),
                ('tags', models.CharField(max_length=2000)),
                ('bekeken', models.IntegerField(blank=True, null=True)),
                ('bewaard', models.IntegerField(blank=True, null=True)),
                ('kookgroepen', models.IntegerField(blank=True, null=True)),
                ('kookboeken', models.IntegerField(blank=True, null=True)),
                ('beoordeling_avg', models.IntegerField(blank=True, null=True)),
                ('beoordeling_aantal', models.IntegerField(blank=True, null=True)),
                ('reactie_aantal', models.IntegerField(blank=True, null=True)),
                ('reacties', models.CharField(max_length=2000)),
                ('listing_url', models.ForeignKey(db_column='page_url', on_delete=django.db.models.deletion.CASCADE, to='collector.SmulWebPage')),
            ],
        ),
    ]
